#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "datalab";
$SERVER_NAME = "changeme.kangwon.ac.kr";
$SERVER_PORT = 8081;
$COURSE_NAME = "systemprogramming";
$AUTOGRADE_TIMEOUT = 0;
1;
